spring:
  profiles:
    active: local
    group:
      local: local, datasource, auth, s3, kakao-map
      prod: prod, datasource, auth, s3, kakao-map
  config:
    import: optional:file:.env[.properties]

  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Asia/Seoul

server:
  base-uri: ${SERVER_URI}
ai:
  server-uri: ${AI_SERVER_URI}

youtube:
  key: ${YOUTUBE_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com
  model: gpt-4o-mini

cors:
  allowed-origins: http://localhost:3000, https://readingtown.site, https://dev.readingtown.site

resilience4j:
  retry:
    instances:
      redisRetry:
        maxAttempts: 3
        waitDuration: 100ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        # 1차: 100ms, 2차: 200ms, 3차: 400ms
      aiRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        # 1차: 1s, 2차: 2s, 3차:

  circuitbreaker:
    instances:
      redisCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
      aiCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3