spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF